# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://github.com/dpatino00/dpatino00.github.io'
baseurl: ''
title: "Daniel Patino's Website"
description: 'This is my new website'
permalink: pretty
repo: 'https://github.com/dpatino00/dpatino00.github.io'

##### NAVIGATION #####
# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Resume
  url: /resume/
- title: Search
  url: /search/
- title: About Me
  url: /about/

# Footer nav
navigation_footer:
- title: LinkedIn
  url: "https://www.linkedin.com/in/daniel-patino-a0a7461bb/"
- title: GitHub
  url: "https://github.com/dpatino00"
- title: Back to top
  url: "#top"

#### SOCIAL MEDIA LINKS ####
# Social media links
social_links:
- title: LinkedIn
  url: "https://www.linkedin.com/in/daniel-patino-a0a7461bb/"

sharing_links:
  LinkedIn: "#0077b5"
  X (Twitter): "#0d94e7"
  email: True

#### Collections ####
# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: "Welcome to my blog!"
    feature_image: "/images/blog.jpg"
# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# Pagination for blog
paginate: 5
paginate_path: blog/page:num

# sass settings; quiet_deps: true will suppress warnings about missing dependencies
sass:
  quiet_deps: true
  style: compressed
  permalink: pretty
  excerpt_separator: "<!--more-->"
  timezone: America/New_York
